# Build stage
FROM node:18 as build

WORKDIR /frontend
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage (serve with Nginx)
FROM nginx:stable-alpine

# Copy build output to nginx html folder
COPY --from=build /frontend/dist /usr/share/nginx/html

# Copy default nginx config (optional: to handle React routing)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]