# Use Python base image
FROM python:3.11-slim

# Set work directory
WORKDIR /backend

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python3 -c "from transformers import pipeline; pipeline(task = 'zero-shot-classification', model = 'MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7');"

# Copy project files
COPY ./src ./src
COPY ./public ./public

# Expose FastAPI port
EXPOSE 8000

# Run with Uvicorn
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]